Add candidates table
Politica-Para-Todos/comentAR pull request #47
Opened 2019-09-19 22:25 UTC by inesrosete

2019-09-19 22:53 UTC, punnie requested changes
The comments I left are nice to haves.

However, you need to add the `party_id` to the candidate table or the association of the candidate with the party won't work.

You can achieve this by adding a `references` field on the `candidates` table, this way:

```ruby
def change
  add_reference :candidates, :party, index: true
end
```

2019-09-19 22:53 UTC, punnie commented on db/migrate/20190918220809_create_candidates.rb
> +      t.boolean :isLeadCandidate
Ruby convention is snake case, therefore: `:is_lead_candidate` is preferred.

2019-09-19 22:53 UTC, punnie commented on db/migrate/20190918220809_create_candidates.rb
> +      t.string :candidateType
Ruby convention is snake case, therefore: `:candidate_type` is preferred.

2019-09-22 08:50 UTC, inesrosete commented
@punnie Candidates table doesn't show in the admin page, do you know why?

2019-09-22 18:20 UTC, punnie approved these changes

2019-09-22 18:20 UTC, merged